# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 431043e6552d18164894f366644d51f6d941595a96ae906f27c962fc01daa7133469c642209ffa95077a50eca6038c2a6aae8c7fcae44f36c9b1654286c88794

test:
  secret_key_base: 2f88dd084f3369a9a3010759397558f216227d1188897faffb715ba07607498c61f3fbbfd75537ff67a957634e7757915c9a4aa195a96d7bbf3f903bf2023102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
